#configuration
server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbreporting
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jwt:
  token:
    expired: 3600000
    refreshToken: 360000000
    secret: secret123
internal:
  namingApiKey: apiKey
  namingAuthorization: Authorization
  apiKey: 9f63ac218-624e-490c-bffb-972730243938
uri:
  surrounding:
    recruitment-position: http://dev3.dansmultipro.co.id/api/recruitment/positions.json
